services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: smartstart-postgres
    environment:
      POSTGRES_DB: smartstart_db
      POSTGRES_USER: smartstart_user
      POSTGRES_PASSWORD: smartstart_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smartstart-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartstart_user -d smartstart_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Python Brain Service
  python-brain:
    build:
      context: ./python-services
      dockerfile: Dockerfile
    container_name: smartstart-python-brain
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://smartstart_user:smartstart_password@postgres:5432/smartstart_db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
    ports:
      - "5001:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - smartstart-network
    volumes:
      - ./python-services:/app
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  smartstart-network:
    driver: bridge
