version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: smartstart_test
    ports: ["5433:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-test:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/smartstart_test
      NODE_ENV: test
      TEST_DATABASE_URL: postgresql://postgres:postgres@db:5432/smartstart_test
    command: sh -c "npx prisma migrate reset --force && pnpm --filter @smartstart/api test:run"
    volumes:
      - ./apps/api:/app/apps/api
      - ./prisma:/app/prisma
