services:
  - name: smartstart-api
    type: web
    runtime: node
    plan: starter
    buildCommand: npm install --production && npx prisma generate
    startCommand: npm run start:api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: DATABASE_URL
        fromDatabase:
          name: smartstart-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: WORKER_ENABLED
        value: "false"
      - key: STORAGE_ENABLED
        value: "false"
      - key: MONITOR_ENABLED
        value: "false"
    autoDeploy: true

databases:
  - name: smartstart-db
    plan: starter
    databaseName: smartstart
