services:
  # Main AliceSolutionsGroup Website (Node.js + Vite)
  - type: web
    name: alicesolutionsgroup-website
    env: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: cd stellar-den && pnpm install && pnpm build
    startCommand: cd stellar-den && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: PRODUCTION_DOMAIN
        value: https://alicesolutionsgroup.com
    healthCheckPath: /
    autoDeploy: true
