services:
  - type: web
    name: smartstart-web
    env: node
    rootDir: apps/web
    plan: free
    buildCommand: pnpm install && pnpm --filter @smartstart/web build
    startCommand: pnpm --filter @smartstart/web start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: smartstart-api
          type: web
          property: url
      - key: WEB_ORIGIN
        fromService:
          name: smartstart-web
          type: web
          property: url
    autoDeploy: true

  - type: web
    name: smartstart-api
    env: node
    rootDir: apps/api
    plan: free
    buildCommand: corepack enable && pnpm install && pnpm prisma:generate
    startCommand: pnpm prisma:migrate && pnpm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartstart-db
          property: connectionString
      - key: PORT
        value: 3001
      - key: WEB_ORIGIN
        fromService:
          name: smartstart-web
          type: web
          property: url
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true

databases:
  - name: smartstart-db
    plan: free
    ipAllowList: []
