services:
  - type: web
    name: smartstart-website
    env: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: |
      cd smartstart-platform && 
      npm ci --production --cache .npm-cache --prefer-offline &&
      cd Quiestioneer && 
      npm ci --production --cache .npm-cache --prefer-offline &&
      npm run build
    startCommand: cd smartstart-platform && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3346
      - key: WEBSITE_PORT
        value: 3346
      - key: PRODUCTION_DOMAIN
        value: https://alicesolutionsgroup.com
      - key: QUIESTIONEER_PORT
        value: 3347
    healthCheckPath: /
    autoDeploy: true