# SmartStart Website - Render Blueprint Configuration
# Simple deployment for the public website only

services:
  # SmartStart Website (Public-facing)
  - type: web
    name: smartstart-website
    env: node
    plan: starter
    region: oregon
    buildCommand: |
      echo "🚀 Building SmartStart Website..."
      cd smartstart-platform
      npm ci --production --cache .npm-cache --prefer-offline
      echo "✅ Website build complete"
    startCommand: cd smartstart-platform && node website-server.js
    autoDeploy: true
    branch: main
    healthCheckPath: /
    healthCheckGracePeriod: 300
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"