services:
  - name: smartstart-api
    type: web
    runtime: node
    plan: free
    buildCommand: npm install --production && npx prisma generate
    startCommand: npm run start:api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
    autoDeploy: true
