# SmartStart Platform - Render.com Blueprint

# Define databases separately
databases:
  - name: smartstart-db
    plan: free

# Define services separately
services:
  - name: smartstart-api
    type: web
    runtime: node
    plan: free
    buildCommand: npm ci --only=production
    startCommand: npm run start:api
    envVars:
      - key: DATABASE_URL
        value: "postgresql://placeholder"
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: API_PORT
        value: "3001"
      - key: NODE_ENV
        value: "production"
    healthCheckPath: /api/health
    autoDeploy: true

  - name: smartstart-platform
    type: web
    runtime: node
    plan: free
    buildCommand: npm ci --only=production && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: "postgresql://placeholder"
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: "https://smartstart-platform.onrender.com"
      - key: NEXT_PUBLIC_API_URL
        value: "https://smartstart-api.onrender.com"
      - key: NODE_ENV
        value: "production"
    healthCheckPath: /
    autoDeploy: true
