services:
  - name: smartstart-api
    type: web
    runtime: node
    plan: standard
    buildCommand: npm ci --omit=dev && npx prisma generate
    startCommand: npm run start:api
    healthCheckPath: /health
    healthCheckTimeout: 300
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        fromDatabase:
          name: smartstart-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://smartstart-cli-web.onrender.com
      - key: WORKER_ENABLED
        value: "false"
      - key: STORAGE_ENABLED
        value: "false"
      - key: MONITOR_ENABLED
        value: "false"

  - name: smartstart-cli-web
    type: web
    runtime: node
    plan: starter
    # Need devDependencies (tailwindcss/postcss/autoprefixer) at build time
    buildCommand: NPM_CONFIG_PRODUCTION=false npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: NEXT_PUBLIC_API_URL
        value: https://smartstart-api.onrender.com
    autoDeploy: true

databases:
  - name: smartstart-db
    plan: basic-256mb
    databaseName: smartstart
