services:
  - type: web
    name: smartstart-website
    env: node
    plan: starter
    region: oregon
    rootDir: smartstart-platform
    buildCommand: npm ci --production --cache .npm-cache --prefer-offline
    startCommand: npm start
    autoDeploy: true
    branch: main
    healthCheckPath: /
    healthCheckGracePeriod: 300
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"