services:
  - type: web
    name: smartstart-api
    env: node
    plan: starter
    buildCommand: npm install --production && npx prisma generate && npx prisma db push --accept-data-loss
    startCommand: node server/python-proxy-server.js
    autoDeploy: true
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://smartstart_db_4ahd_user:LYcgYXd9w9pBB4HPuNretjMOOlKxWP48@dpg-d2uaqd6r433s73e56vfg-a.oregon-postgres.render.com:5432/smartstart_db_4ahd?sslmode=require
      - key: PYTHON_BRAIN_URL
        value: https://smartstart-python-brain.onrender.com
      # DATABASE_URL is set in Render dashboard; omit here to preserve secret
  - type: web
    name: smartstart-python-brain
    env: python
    plan: starter
    buildCommand: cd python-services && pip install --cache-dir .pip-cache --no-deps --upgrade -r requirements.txt
    startCommand: cd python-services && python start.py
    autoDeploy: true
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: NODEJS_API_URL
        value: https://smartstart-api.onrender.com
      - key: CORS_ORIGINS
        value: "https://smartstart-frontend.onrender.com,http://localhost:3000"
      - key: PYTHON_BRAIN_VERSION
        value: "2.1.2"
      # DATABASE_URL is set in Render dashboard; omit here to preserve secret
  - type: web
    name: smartstart-frontend
    env: node
    plan: starter
    buildCommand: cd frontend && chmod +x build-simple.sh && ./build-simple.sh
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://smartstart-python-brain.onrender.com
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    # Health check configuration
    healthCheckPath: /
    # Auto-deploy from main branch
    autoDeploy: true
    # Branch configuration
    branch: main