services:
  - name: smartstart-db
    type: pserv
    runtime: postgres
    plan: starter
    startCommand: postgres
    autoDeploy: true

  - name: smartstart-api
    type: web
    runtime: node
    plan: starter
    buildCommand: npm install --production && npx prisma generate
    startCommand: npm run start:api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: DATABASE_URL
        fromService:
          name: smartstart-db
          type: pserv
          property: host
      - key: DB_PORT
        fromService:
          name: smartstart-db
          type: pserv
          property: port
      - key: DB_NAME
        value: "smartstart"
      - key: DB_USER
        value: "postgres"
      - key: DB_PASSWORD
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: WORKER_ENABLED
        value: "false"
      - key: STORAGE_ENABLED
        value: "false"
      - key: MONITOR_ENABLED
        value: "false"
    autoDeploy: true
