# SmartStart Platform - Render.com Free Plan Optimized
# Maximum 3 services for free tier compliance
# Free tier: 750 hours/month, 512MB RAM, shared CPU

databases:
  - name: smartstart-db
    plan: free
    ipAllowList: []

services:
  # Consolidated API Server - Handles all backend functionality in one service
  # This consolidates api.js, worker.js, storage.js, and monitor.js into one service
  - name: smartstart-api
    type: web
    runtime: node
    plan: free
    buildCommand: npm ci --only=production && npx prisma generate
    startCommand: npm run start:api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartstart-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: API_PORT
        value: "3001"
      - key: NODE_ENV
        value: production
      - key: WORKER_ENABLED
        value: "true"
      - key: STORAGE_ENABLED
        value: "true"
      - key: MONITOR_ENABLED
        value: "true"
      - key: AWS_ACCESS_KEY_ID
        value: "" # Add your AWS credentials when ready
      - key: AWS_SECRET_ACCESS_KEY
        value: "" # Add your AWS credentials when ready
      - key: AWS_S3_BUCKET
        value: "smartstart-files"
      - key: AWS_REGION
        value: "us-east-1"
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: "" # Add your email when ready
      - key: SMTP_PASS
        value: "" # Add your email password when ready
    healthCheckPath: /api/health
    autoDeploy: true
    # Free tier optimizations
    maxInstances: 1
    minInstances: 0

  # Web Service - Next.js frontend application
  - name: smartstart-platform
    type: web
    runtime: node
    plan: free
    buildCommand: npm ci --only=production && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartstart-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://smartstart-platform.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://smartstart-api.onrender.com
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    # Free tier optimizations
    maxInstances: 1
    minInstances: 0
