services:
  # ============================================================================
  # EXISTING MAIN WEBSITE - smartstart-website (kept as-is, matching current Render)
  # ============================================================================
  - type: web
    name: smartstart-website
    env: node
    plan: starter
    region: oregon
    branch: main
    rootDir: stellar-den
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      # Analytics Hub Server URL
      - key: VITE_ANALYTICS_API_URL
        value: https://analytics-hub-server.onrender.com
    healthCheckPath: /health
    autoDeploy: true
  # ============================================================================
  # ANALYTICS HUB - Backend Server
  # ============================================================================
  - type: web
    name: analytics-hub-server
    env: node
    plan: starter
    region: oregon
    branch: main
    rootDir: analytics-hub
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: analytics-hub-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ADMIN_EMAIL
        value: udi.shkolnik@alicesolutionsgroup.com
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://alicesolutionsgroup.com,https://www.alicesolutionsgroup.com,https://analytics-hub-dashboard.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
    healthCheckPath: /health
    autoDeploy: true

  # ============================================================================
  # ANALYTICS HUB - Admin Dashboard (Static Site)
  # ============================================================================
  - type: web
    name: analytics-hub-dashboard
    env: static
    # region is not supported for static services
    branch: main
    rootDir: analytics-hub/client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://analytics-hub-server.onrender.com
      - key: VITE_WS_URL
        value: wss://analytics-hub-server.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    autoDeploy: true

# ============================================================================
# DATABASE - PostgreSQL for Analytics Hub
# ============================================================================
databases:
  - name: analytics-hub-db
    region: oregon
    databaseName: analytics_hub
    user: analytics_admin
    ipAllowList: []
    postgresMajorVersion: 15