# SmartStart Database Service - Clean Configuration
# Version: 2.0 - Clean Database-Only Setup
# Deployed: September 1, 2025

services:
  - type: web
    name: smartstart-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push && npx prisma db seed && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: smartstart-db
          property: connectionString
      - key: PORT
        value: 8080

databases:
  - name: smartstart-db
    plan: free
