services:
  - name: smartstart-api
    type: web
    runtime: node
    plan: free
    buildCommand: npm ci --only=production
    startCommand: npm run start:api
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
