services:
  - type: web
    name: smartstart-frontend
    env: node
    plan: starter
    buildCommand: cd frontend && chmod +x build-simple.sh && ./build-simple.sh
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://smartstart-api.onrender.com
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    # Health check configuration
    healthCheckPath: /
    # Auto-deploy from main branch
    autoDeploy: true
    # Branch configuration
    branch: main