services:
  - type: web
    name: smartstart-frontend
    env: node
    plan: starter
    buildCommand: cd frontend && chmod +x build-render.sh && ./build-render.sh
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://smartstart-api.onrender.com
    # Enable build caching
    buildCache:
      enabled: true
    # Optimize build performance
    buildSettings:
      buildCommand: |
        cd frontend
        npm ci --only=production --no-audit --no-fund
        npm run build
      installCommand: npm ci --only=production --no-audit --no-fund