services:
  - type: web
    name: smartstart-database
    env: node
    rootDir: .
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push && npx prisma db seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: smartstart-db
          property: connectionString
      - key: PORT
        value: 8080

databases:
  - name: smartstart-db
    plan: free
