services:
  - type: web
    name: smartstart-website
    env: node
    plan: starter
    buildCommand: cd smartstart-platform && npm install
    startCommand: cd smartstart-platform && npm start
    envVars:
      - key: NODE_ENV
        value: production