# SmartStart Platform - Free Plan Compatible Blueprint
# Optimized for Render.com free tier with consolidated services

databases:
  - name: smartstart-db
    plan: free
    ipAllowList: []

services:
  # Main API Server - Handles all business logic, database operations, and background jobs
  - name: smartstart-api
    type: web
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm run start:api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartstart-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: API_PORT
        value: "3001"
      - key: NODE_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        value: "sk_test_..." # Add your Stripe test key
      - key: GITHUB_CLIENT_ID
        value: "" # Add your GitHub OAuth app ID
      - key: GITHUB_CLIENT_SECRET
        value: "" # Add your GitHub OAuth secret
      - key: M365_CLIENT_ID
        value: "" # Add your Microsoft 365 app ID
      - key: M365_CLIENT_SECRET
        value: "" # Add your Microsoft 365 secret
      - key: SMTP_HOST
        value: "smtp.gmail.com" # Email service
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: "" # Add your email
      - key: SMTP_PASS
        value: "" # Add your email password
      - key: REDIS_URL
        value: "" # For caching and sessions
      - key: AWS_ACCESS_KEY_ID
        value: "" # Add your AWS credentials
      - key: AWS_SECRET_ACCESS_KEY
        value: "" # Add your AWS credentials
      - key: AWS_S3_BUCKET
        value: "smartstart-files" # S3 bucket for file storage
      - key: AWS_REGION
        value: "us-east-1"
      - key: STORAGE_PORT
        value: "3002"
      - key: MONITOR_PORT
        value: "3003"
      - key: WORKER_ENABLED
        value: "true"
      - key: STORAGE_ENABLED
        value: "true"
      - key: MONITOR_ENABLED
        value: "true"
    healthCheckPath: /api/health
    autoDeploy: true

  # Web Service - Next.js frontend application
  - name: smartstart-platform
    type: web
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartstart-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://smartstart-platform.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://smartstart-api.onrender.com
      - key: NODE_ENV
        value: production
      - key: STRIPE_PUBLISHABLE_KEY
        value: "pk_test_..." # Add your Stripe publishable key
      - key: NEXT_PUBLIC_S3_BUCKET
        value: "smartstart-files"
      - key: NEXT_PUBLIC_AWS_REGION
        value: "us-east-1"
    healthCheckPath: /
    autoDeploy: true

  # Database Migration Service - Handles database setup and seeding
  - name: smartstart-database
    type: web
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push --force-reset && npx prisma db seed
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartstart-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true
