services:
  - type: web
    name: smb-cyber-health-check
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./smb_health_check.db
      - key: MAX_ASSESSMENTS_PER_IP
        value: 10
      - key: RATE_LIMIT_WINDOW
        value: 3600
    
    # Health check
    healthCheckPath: /health
    
    # Auto-deploy
    autoDeploy: true
    
    # Build settings
    buildCommand: echo "Using Docker build"
    
    # Custom domains (configure as needed)
    # customDomains:
    #   - smbcybercheck.com
    #   - www.smbcybercheck.com